try {
  const a = 1;
  a = 2;
} catch {
  console.error("catch");
}